<h1>Example: Atmospheric correction of the GOES-16 ABI visible bands with Pyspectral</h1>

In [11]:
from pyspectral import rayleigh

In [3]:
import numpy as np

In [4]:
sunz = np.array([[50., 60.], [50., 60.]])

In [5]:
satz = np.array([[40., 50.], [40., 50.]])

In [6]:
azidiff = np.array([[160, 160], [20, 20]])

<h2>Using default atmosphere and aerosol load: midlatitude summer and marine-clean aerosols</h2>

In [2]:
corr = rayleigh.Rayleigh('GOES-16', 'abi')

In [7]:
print corr.get_reflectance(sunz, satz, azidiff, 'ch1')

[[  7.66551598  11.84851174]
 [ 12.30975667  17.83044933]]


In [10]:
print corr.get_reflectance(sunz, satz, azidiff, 'ch2')

[[ 2.01927932  3.20415785]
 [ 3.52058364  5.18308456]]


In [9]:
print corr.get_reflectance(sunz, satz, azidiff, 'ch3')

[[ 0.  0.]
 [ 0.  0.]]


No handlers could be found for logger "pyspectral.rayleigh"


<h2>Select atmosphere and aerosol load</h2>

In [12]:
corr = rayleigh.Rayleigh('GOES-16', 'abi', atmosphere='midlatitude summer', rural_aerosol=True)

In [13]:
print corr.get_reflectance(sunz, satz, azidiff, 'ch1')

[[  7.70954613  11.91336894]
 [ 12.37420018  17.92015488]]
